version: "2"

run:
  timeout: 10m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Kubedoll-Heavy-Industries/mcp-helm

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
