name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Start the server with `mcp-helm --transport=http`
        2. Call tool `search_charts` with...
        3. See error...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MCP Helm Version
      description: What version of mcp-helm are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Server Mode
      description: Which transport mode are you using?
      options:
        - stdio
        - http
        - sse (deprecated)
    validations:
      required: true

  - type: input
    id: client
    attributes:
      label: MCP Client
      description: What MCP client are you using?
      placeholder: "Claude Desktop, VS Code, Cursor, etc."
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Docker/Container
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output (server logs, client errors, etc.)
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (config files, environment variables, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true
        - label: I am using a supported version of mcp-helm
          required: true
