name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it enable?
      placeholder: |
        I'm trying to accomplish X, but currently...

        As an AI agent working with Helm charts, I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I would like a new tool called `render_chart` that...

        The API should accept these parameters:
        - chart_name (required)
        - version (optional)
        - values (optional, inline YAML)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Tool
        - New Resource
        - New Prompt
        - Performance Improvement
        - Security Enhancement
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered or tried?
      placeholder: |
        I tried working around this by...

        Another option would be...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that would help explain the feature

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature via a pull request
